language: go
env:
  - PATH=$GOPATH/bin:$PATH
  - OMISE_PKEY=pkey_test_xxx
  - OMISE_SKEY=skey_test_xxx
script:
  - go get github.com/alecthomas/gometalinter
  - go get github.com/jteeuwen/go-bindata/go-bindata
  - gometalinter --install
  - ./build.sh
go:
- "tip"
- "1.6"
- "1.7"
- "1.8"
