/*
!!! DO NOT MODIFY !!!

autogenerated
 src: gen_list_job.tmpl
 job: &main.GenListJob{Name:"Account"}
  on: Thu Nov 05 09:53:07 +0700 2015
  by: chakrit
*/

package omise

type AccountList struct {
	List
  Data []*Account `json:"data"`
}

func (list *AccountList) Find(id string) *Account {
	for _, item := range list.Data {
		if item.ID == id {
			return item
		}
	}

	return nil
}

