package omise

/*
!!! DO NOT MODIFY !!!

autogenerated
 src: gen_list_job.tmpl
 job: &main.GenListJob{Name:"Account"}
  on: Fri Nov 06 13:48:24 +0700 2015
  by: chakrit
*/

// AccountList represents the list structure returned by Omise's REST API that contains
// Account struct as member elements. See the pagination and lists documentation at
// https://www.omise.co/api-pagination for more information.
type AccountList struct {
	List
	Data []*Account `json:"data"`
}

// Find finds and returns Account with the given id. Returns nil if not found.
func (list *AccountList) Find(id string) *Account {
	for _, item := range list.Data {
		if item.ID == id {
			return item
		}
	}

	return nil
}
