/*
!!! DO NOT MODIFY !!!

autogenerated
 src: gen_list_job.tmpl
 job: &main.GenListJob{Name:"Balance"}
  on: Thu Nov 05 09:53:07 +0700 2015
  by: chakrit
*/

package omise

type BalanceList struct {
	List
  Data []*Balance `json:"data"`
}

func (list *BalanceList) Find(id string) *Balance {
	for _, item := range list.Data {
		if item.ID == id {
			return item
		}
	}

	return nil
}

