/*
!!! DO NOT MODIFY !!!

autogenerated
 src: gen_list_job.tmpl
 job: &main.GenListJob{Name:"BankAccount"}
  on: Thu Nov 05 09:53:07 +0700 2015
  by: chakrit
*/

package omise

type BankAccountList struct {
	List
  Data []*BankAccount `json:"data"`
}

func (list *BankAccountList) Find(id string) *BankAccount {
	for _, item := range list.Data {
		if item.ID == id {
			return item
		}
	}

	return nil
}

