/*
!!! DO NOT MODIFY !!!

autogenerated
 src: gen_list_job.tmpl
 job: &main.GenListJob{Name:"Card"}
  on: Thu Nov 05 09:53:07 +0700 2015
  by: chakrit
*/

package omise

type CardList struct {
	List
  Data []*Card `json:"data"`
}

func (list *CardList) Find(id string) *Card {
	for _, item := range list.Data {
		if item.ID == id {
			return item
		}
	}

	return nil
}

