/*
!!! DO NOT MODIFY !!!

autogenerated
on: Thu Nov 05 02:49:57 +0000 2015
by: chakrit
*/

package omise

type CardList struct {
	List
  Data []*Card `json:"data"`
}

func (list *CardList) Find(id string) *Card {
	for _, item := range list.Data {
		if item.ID == id {
			return item
		}
	}

	return nil
}

