/*
!!! DO NOT MODIFY !!!

autogenerated
 src: gen_list_job.tmpl
 job: &main.GenListJob{Name:"Charge"}
  on: Thu Nov 05 09:53:07 +0700 2015
  by: chakrit
*/

package omise

type ChargeList struct {
	List
  Data []*Charge `json:"data"`
}

func (list *ChargeList) Find(id string) *Charge {
	for _, item := range list.Data {
		if item.ID == id {
			return item
		}
	}

	return nil
}

