/*
!!! DO NOT MODIFY !!!

autogenerated
 src: gen_list_job.tmpl
 job: &main.GenListJob{Name:"Dispute"}
  on: Thu Nov 05 09:53:07 +0700 2015
  by: chakrit
*/

package omise

type DisputeList struct {
	List
  Data []*Dispute `json:"data"`
}

func (list *DisputeList) Find(id string) *Dispute {
	for _, item := range list.Data {
		if item.ID == id {
			return item
		}
	}

	return nil
}

