/*
!!! DO NOT MODIFY !!!

autogenerated
on: Thu Nov 05 02:49:57 +0000 2015
by: chakrit
*/

package omise

type DisputeList struct {
	List
  Data []*Dispute `json:"data"`
}

func (list *DisputeList) Find(id string) *Dispute {
	for _, item := range list.Data {
		if item.ID == id {
			return item
		}
	}

	return nil
}

