package omise

/*
!!! DO NOT MODIFY !!!

autogenerated
 src: gen_search_job.tmpl
 job: &main.GenSearchJob{Names:[]string{"Charge", "Customer", "Dispute", "Recipient"}}
  on: Thu Mar 02 13:31:35 +0700 2017
  by: chakrit
*/

import (
	"bytes"
)

// SearchScope can be one of the following constants:
const (
	UnspecifiedScope SearchScope = ""

	ChargeScope    SearchScope = "charge"
	CustomerScope  SearchScope = "customer"
	DisputeScope   SearchScope = "dispute"
	RecipientScope SearchScope = "recipient"
)

// ChargeSearchResult represents search result structure returned by Omise's Search API
// that contains Charge struct as result elements.
type ChargeSearchResult struct {
	SearchResult
	Data []*Charge `json:"data"`
}

func (list *ChargeSearchResult) String() string {
	buf := &bytes.Buffer{}
	for _, item := range list.Data {
		buf.WriteString(item.String() + "\n")
	}
	return buf.String()
}

// CustomerSearchResult represents search result structure returned by Omise's Search API
// that contains Customer struct as result elements.
type CustomerSearchResult struct {
	SearchResult
	Data []*Customer `json:"data"`
}

func (list *CustomerSearchResult) String() string {
	buf := &bytes.Buffer{}
	for _, item := range list.Data {
		buf.WriteString(item.String() + "\n")
	}
	return buf.String()
}

// DisputeSearchResult represents search result structure returned by Omise's Search API
// that contains Dispute struct as result elements.
type DisputeSearchResult struct {
	SearchResult
	Data []*Dispute `json:"data"`
}

func (list *DisputeSearchResult) String() string {
	buf := &bytes.Buffer{}
	for _, item := range list.Data {
		buf.WriteString(item.String() + "\n")
	}
	return buf.String()
}

// RecipientSearchResult represents search result structure returned by Omise's Search API
// that contains Recipient struct as result elements.
type RecipientSearchResult struct {
	SearchResult
	Data []*Recipient `json:"data"`
}

func (list *RecipientSearchResult) String() string {
	buf := &bytes.Buffer{}
	for _, item := range list.Data {
		buf.WriteString(item.String() + "\n")
	}
	return buf.String()
}
