package omise

/*
!!! DO NOT MODIFY !!!

autogenerated
 src: gen_string_job.tmpl
 job: &main.GenStringJob{Fields:map[string][]string{"Account":[]string{"ID", "Live", "Email"}, "Balance":[]string{"ID", "Live", "Available", "Total", "Currency"}, "Link":[]string{"ID", "Live"}, "Refund":[]string{"ID", "Live", "Amount", "Currency", "Charge"}, "Transaction":[]string{"ID", "Live", "Source", "Type", "Amount", "Currency", "Transferable"}, "Transfer":[]string{"ID", "Live", "Recipient", "Sent", "Paid", "Fee", "Amount", "Currency"}, "BankAccount":[]string{"ID", "Live", "Brand", "LastDigits", "Name"}, "Customer":[]string{"ID", "Live", "Email", "Description"}, "Token":[]string{"ID", "Live", "Used", "Card"}, "Charge":[]string{"ID", "Live", "Amount", "Currency", "Capture", "Authorized", "Reversed", "Paid"}, "Deletion":[]string{"ID", "Live", "Deleted"}, "Dispute":[]string{"ID", "Live", "Amount", "Currency", "Status", "Charge"}, "Document":[]string{"ID", "Live", "Filename"}, "Recipient":[]string{"ID", "Live", "Name", "Email", "Type"}, "Card":[]string{"ID", "Live", "LastDigits", "Brand", "ExpirationMonth", "ExpirationYear", "Name"}, "Event":[]string{"ID", "Live", "Key", "Data"}}}
  on: Thu Mar 02 13:31:35 +0700 2017
  by: chakrit
*/

import "fmt"

func (m *Account) String() string {
	return "" +
		"ID=" + fmt.Sprint(m.ID) + " " +
		"Live=" + fmt.Sprint(m.Live) + " " +
		"Email=" + fmt.Sprint(m.Email) + " " + ""
}

func (m *Balance) String() string {
	return "" +
		"ID=" + fmt.Sprint(m.ID) + " " +
		"Live=" + fmt.Sprint(m.Live) + " " +
		"Available=" + fmt.Sprint(m.Available) + " " +
		"Total=" + fmt.Sprint(m.Total) + " " +
		"Currency=" + fmt.Sprint(m.Currency) + " " + ""
}

func (m *BankAccount) String() string {
	return "" +
		"ID=" + fmt.Sprint(m.ID) + " " +
		"Live=" + fmt.Sprint(m.Live) + " " +
		"Brand=" + fmt.Sprint(m.Brand) + " " +
		"LastDigits=" + fmt.Sprint(m.LastDigits) + " " +
		"Name=" + fmt.Sprint(m.Name) + " " + ""
}

func (m *Card) String() string {
	return "" +
		"ID=" + fmt.Sprint(m.ID) + " " +
		"Live=" + fmt.Sprint(m.Live) + " " +
		"LastDigits=" + fmt.Sprint(m.LastDigits) + " " +
		"Brand=" + fmt.Sprint(m.Brand) + " " +
		"ExpirationMonth=" + fmt.Sprint(m.ExpirationMonth) + " " +
		"ExpirationYear=" + fmt.Sprint(m.ExpirationYear) + " " +
		"Name=" + fmt.Sprint(m.Name) + " " + ""
}

func (m *Charge) String() string {
	return "" +
		"ID=" + fmt.Sprint(m.ID) + " " +
		"Live=" + fmt.Sprint(m.Live) + " " +
		"Amount=" + fmt.Sprint(m.Amount) + " " +
		"Currency=" + fmt.Sprint(m.Currency) + " " +
		"Capture=" + fmt.Sprint(m.Capture) + " " +
		"Authorized=" + fmt.Sprint(m.Authorized) + " " +
		"Reversed=" + fmt.Sprint(m.Reversed) + " " +
		"Paid=" + fmt.Sprint(m.Paid) + " " + ""
}

func (m *Customer) String() string {
	return "" +
		"ID=" + fmt.Sprint(m.ID) + " " +
		"Live=" + fmt.Sprint(m.Live) + " " +
		"Email=" + fmt.Sprint(m.Email) + " " +
		"Description=" + fmt.Sprint(m.Description) + " " + ""
}

func (m *Deletion) String() string {
	return "" +
		"ID=" + fmt.Sprint(m.ID) + " " +
		"Live=" + fmt.Sprint(m.Live) + " " +
		"Deleted=" + fmt.Sprint(m.Deleted) + " " + ""
}

func (m *Dispute) String() string {
	return "" +
		"ID=" + fmt.Sprint(m.ID) + " " +
		"Live=" + fmt.Sprint(m.Live) + " " +
		"Amount=" + fmt.Sprint(m.Amount) + " " +
		"Currency=" + fmt.Sprint(m.Currency) + " " +
		"Status=" + fmt.Sprint(m.Status) + " " +
		"Charge=" + fmt.Sprint(m.Charge) + " " + ""
}

func (m *Document) String() string {
	return "" +
		"ID=" + fmt.Sprint(m.ID) + " " +
		"Live=" + fmt.Sprint(m.Live) + " " +
		"Filename=" + fmt.Sprint(m.Filename) + " " + ""
}

func (m *Event) String() string {
	return "" +
		"ID=" + fmt.Sprint(m.ID) + " " +
		"Live=" + fmt.Sprint(m.Live) + " " +
		"Key=" + fmt.Sprint(m.Key) + " " +
		"Data=" + fmt.Sprint(m.Data) + " " + ""
}

func (m *Link) String() string {
	return "" +
		"ID=" + fmt.Sprint(m.ID) + " " +
		"Live=" + fmt.Sprint(m.Live) + " " + ""
}

func (m *Recipient) String() string {
	return "" +
		"ID=" + fmt.Sprint(m.ID) + " " +
		"Live=" + fmt.Sprint(m.Live) + " " +
		"Name=" + fmt.Sprint(m.Name) + " " +
		"Email=" + fmt.Sprint(m.Email) + " " +
		"Type=" + fmt.Sprint(m.Type) + " " + ""
}

func (m *Refund) String() string {
	return "" +
		"ID=" + fmt.Sprint(m.ID) + " " +
		"Live=" + fmt.Sprint(m.Live) + " " +
		"Amount=" + fmt.Sprint(m.Amount) + " " +
		"Currency=" + fmt.Sprint(m.Currency) + " " +
		"Charge=" + fmt.Sprint(m.Charge) + " " + ""
}

func (m *Token) String() string {
	return "" +
		"ID=" + fmt.Sprint(m.ID) + " " +
		"Live=" + fmt.Sprint(m.Live) + " " +
		"Used=" + fmt.Sprint(m.Used) + " " +
		"Card=" + fmt.Sprint(m.Card) + " " + ""
}

func (m *Transaction) String() string {
	return "" +
		"ID=" + fmt.Sprint(m.ID) + " " +
		"Live=" + fmt.Sprint(m.Live) + " " +
		"Source=" + fmt.Sprint(m.Source) + " " +
		"Type=" + fmt.Sprint(m.Type) + " " +
		"Amount=" + fmt.Sprint(m.Amount) + " " +
		"Currency=" + fmt.Sprint(m.Currency) + " " +
		"Transferable=" + fmt.Sprint(m.Transferable) + " " + ""
}

func (m *Transfer) String() string {
	return "" +
		"ID=" + fmt.Sprint(m.ID) + " " +
		"Live=" + fmt.Sprint(m.Live) + " " +
		"Recipient=" + fmt.Sprint(m.Recipient) + " " +
		"Sent=" + fmt.Sprint(m.Sent) + " " +
		"Paid=" + fmt.Sprint(m.Paid) + " " +
		"Fee=" + fmt.Sprint(m.Fee) + " " +
		"Amount=" + fmt.Sprint(m.Amount) + " " +
		"Currency=" + fmt.Sprint(m.Currency) + " " + ""
}
