package omise

/*
!!! DO NOT MODIFY !!!

autogenerated
 src: gen_api_tree.tmpl
 job: &main.GenAPITreeJob{Names:[]string(nil), Operations:map[string][]string{}}
  on: Wed Nov 18 15:13:43 +0700 2015
  by: chakrit
*/

// import (
// 	"bytes"
// )
