/*
!!! DO NOT MODIFY !!!

autogenerated
 src: gen_list_job.tmpl
 job: &main.GenListJob{Name:"Refund"}
  on: Thu Nov 05 09:53:07 +0700 2015
  by: chakrit
*/

package omise

type RefundList struct {
	List
  Data []*Refund `json:"data"`
}

func (list *RefundList) Find(id string) *Refund {
	for _, item := range list.Data {
		if item.ID == id {
			return item
		}
	}

	return nil
}

