package main

import (
	"os/user"
	"time"
)

type Data interface{}

type Context struct {
	Data
	User string
	Time time.Time
}

func NewContext(data Data) (*Context, error) {
	usr, e := user.Current()
	if e != nil {
		return nil, e
	}

	return &Context{data, usr.Username, time.Now().UTC()}, nil
}

func (ctx *Context) Header() string {
	return "/*\n" +
		"!!! DO NOT MODIFY !!!\n\n" +
		"autogenerated\n" +
		"on: " + ctx.Time.Format(time.RubyDate) + "\n" +
		"by: " + ctx.User + "\n" +
		"*/"
}
