package main

import (
	"fmt"
	"os/user"
	"time"
)

type Context struct {
	Data interface{}
	Job  Job

	Src  string
	User string
	Time time.Time
}

func NewContext(job Job) (*Context, error) {
	usr, e := user.Current()
	if e != nil {
		return nil, e
	}

	tmplname, _ := job.Filenames()
	context := &Context{
		Data: job,
		Job:  job,
		Src:  tmplname,
		User: usr.Username,
		Time: time.Now(),
	}

	return context, nil
}

func (ctx *Context) Header() string {
	return "/*\n" +
		"!!! DO NOT MODIFY !!!\n\n" +
		"autogenerated\n" +
		" src: " + ctx.Src + "\n" +
		" job: " + fmt.Sprintf("%#v", ctx.Job) + "\n" +
		"  on: " + ctx.Time.Format(time.RubyDate) + "\n" +
		"  by: " + ctx.User + "\n" +
		"*/"
}
